- name: Install application dependencies
  npm:
    path: '{{ current_release_path }}'
    ci: yes
    production: yes

- name: Run migrations
  command: npm run db:migrate
  args:
    chdir: '{{ current_release_path }}'

- name: Start current deployment process
  command: pm2 start ./dist/index.js --name blog
  args:
    chdir: '{{ current_release_path }}'

- name: Freeze a process list
  command: pm2 save
