- name: Import the NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x jammy main
    state: present

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install PM2
  npm:
    name: pm2
    global: yes
