- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg2
      - sqlite3
    state: present

- name: Populate environment variables
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ os_environment }}"

- name: Populate GitHub token
  lineinfile:
    dest: /etc/environment
    state: present
    line: "GH_TOKEN={{ gh_token }}"
  no_log: yes

- name: Populate secret for session tokens
  lineinfile:
    dest: /etc/environment
    state: present
    line: "SECRET={{ session_secret }}"
  no_log: yes
